.PHONY: clean All

All:
	@echo "----------Building project:[ CppGccTest - Release ]----------"
	@cd "CppGccTest" && "$(MAKE)" -f  "CppGccTest.mk"
clean:
	@echo "----------Cleaning project:[ CppGccTest - Release ]----------"
	@cd "CppGccTest" && "$(MAKE)" -f  "CppGccTest.mk" clean
